import type { AttributeType } from "../../../../../models/commons/Attribute/Attribute";
import type { ConceptValueType } from "../../../../../models/commons/Concept/Concept";
import type { ConceptPreset, CustomTypeOption } from "./attributeForm.types";

export const CONCEPT_TYPE_COMPATIBILITY: Record<ConceptValueType, AttributeType[]> = {
  TEXT: ["TEXT"],
  ENUM: ["ENUM"],
  DATETIME: ["DATE", "DATETIME"],
  NUMBER: ["NUMBER"],
  BOOLEAN: ["BOOLEAN"],
};

export const UNIQUE_SYSTEM_CONCEPT_CODES = new Set([
  "FIRST_NAME",
  "LAST_NAME",
  "GENDER",
  "IDENTITY",
]);

export const CONCEPT_PRESETS: Record<string, ConceptPreset> = {
  FIRST_NAME: {
    forceNameFromConcept: true,
    forcedType: "TEXT",
    allowedTypes: ["TEXT"],
    forcedMaxValues: 1,
    forcedPrimaryField: true,
    forcedRequired: true,
    forcedCategory: false,
    forcedFilter: false,
    forcedSort: true,
    hideType: true,
    hideMaxValues: true,
    hidePrimaryField: true,
    hideRequired: true,
    suggested: {
      casingStrategy: "TITLE_CASE",
      primaryField: true,
      category: false,
      filter: false,
      sort: true,
      required: true,
      editPolicy: "FREE",
      constraintKind: "NONE",
      constraintPayload: { kind: "NONE" },
    },
  },
  LAST_NAME: {
    forceNameFromConcept: true,
    forcedType: "TEXT",
    allowedTypes: ["TEXT"],
    forcedMaxValues: 1,
    forcedPrimaryField: true,
    forcedRequired: true,
    forcedCategory: false,
    forcedFilter: false,
    forcedSort: true,
    hideType: true,
    hideMaxValues: true,
    hidePrimaryField: true,
    hideRequired: true,
    suggested: {
      casingStrategy: "UPPERCASE",
      primaryField: true,
      category: false,
      filter: false,
      sort: true,
      required: true,
      editPolicy: "FREE",
      constraintKind: "NONE",
      constraintPayload: { kind: "NONE" },
    },
  },
  GENDER: {
    forceNameFromConcept: true,
    forcedType: "ENUM",
    allowedTypes: ["ENUM"],
    forcedMaxValues: 1,
    forcedCategory: true,
    forcedFilter: true,
    forcedSort: false,
    hideType: true,
    hideMaxValues: true,
    suggested: {
      primaryField: false,
      category: true,
      filter: true,
      sort: false,
      required: false,
      editPolicy: "RESTRICTED",
      constraintKind: "SET",
      constraintPayload: { kind: "SET", values: ["Homme", "Femme"], strict: true },
    },
  },
  IDENTITY: {
    forceNameFromConcept: true,
    forcedType: "TEXT",
    allowedTypes: ["TEXT"],
    forcedMaxValues: 1,
    forcedEditPolicy: "DERIVED",
    forcedPrimaryField: false,
    forcedRequired: false,
    forcedCategory: false,
    forcedFilter: false,
    forcedSort: false,
    hideType: true,
    hideMaxValues: true,
    hideEditPolicy: true,
    hidePrimaryField: true,
    hideRequired: true,
    suggested: {
      category: false,
      filter: false,
      sort: false,
      required: false,
      editPolicy: "DERIVED",
      constraintKind: "NONE",
      constraintPayload: { kind: "NONE" },
    },
  },
  DEPARTMENT: {
    forceNameFromConcept: true,
    forcedType: "ENUM",
    allowedTypes: ["ENUM"],
    forcedCategory: true,
    forcedFilter: true,
    forcedSort: true,
    suggested: {
      type: "ENUM",
      maxValues: 1,
      primaryField: false,
      category: true,
      filter: true,
      sort: true,
      required: false,
      editPolicy: "FREE",
      constraintKind: "SET",
      constraintPayload: { kind: "SET", values: [], strict: true },
    },
  },
  PROMOTION: {
    forceNameFromConcept: true,
    forcedType: "ENUM",
    allowedTypes: ["ENUM"],
    forcedCategory: true,
    forcedFilter: true,
    forcedSort: true,
    suggested: {
      type: "ENUM",
      maxValues: 1,
      primaryField: false,
      category: true,
      filter: true,
      sort: true,
      required: false,
      editPolicy: "FREE",
      constraintKind: "SET",
      constraintPayload: { kind: "SET", values: [], strict: true },
    },
  },
  ARRIVAL_DATE: {
    forceNameFromConcept: true,
    forcedType: "DATE",
    allowedTypes: ["DATE"],
    forcedMaxValues: 1,
    forcedCategory: false,
    forcedFilter: true,
    forcedSort: true,
    hideMaxValues: true,
    suggested: {
      type: "DATE",
      primaryField: false,
      category: false,
      filter: true,
      sort: true,
      required: false,
      editPolicy: "FREE",
      constraintKind: "NONE",
      constraintPayload: { kind: "NONE" },
    },
  },
};

export const CUSTOM_TYPE_OPTIONS: CustomTypeOption[] = [
  { type: "TEXT", label: "Texte", description: "Information textuelle simple" },
  { type: "ENUM", label: "Liste de choix", description: "Valeur choisie dans une liste" },
  { type: "NUMBER", label: "Nombre", description: "Valeur numérique" },
  { type: "DATE", label: "Date", description: "Date sans heure" },
  { type: "DATETIME", label: "Date & heure", description: "Date avec heure" },
  { type: "BOOLEAN", label: "Oui / Non", description: "Réponse binaire" },
];